add navbar
CoreX20/Binar pull request #2
Opened 2024-03-25 15:34 UTC by amiqbal7

2024-03-25 15:37 UTC, CoreX20 commented on index.html
> +            <button class="btn btn-outline-success bg-success text-white" type="submit">Register</button>
change button color to blue

2024-03-25 15:38 UTC, CoreX20 requested changes

2024-03-25 15:38 UTC, CoreX20 commented on index.html
> +            <button class="btn btn-outline-success bg-success text-white" type="submit">Register</button>
change button color to blue

2024-03-26 13:03 UTC, amiqbal7 reviewed
okey

2024-03-26 13:03 UTC, amiqbal7 commented on index.html
> +            <button class="btn btn-outline-success bg-success text-white" type="submit">Register</button>
okey

2024-03-26 13:10 UTC, merged